# Data Filtering and Selection

In [1]:
!pip install --upgrade pip
!pip install numpy
!pip install pandas

Requirement already satisfied: pip in d:\tutorials\ai - engineer\data_science_and_ml\.venv\lib\site-packages (24.0)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
    --------------------------------------- 0.0/1.8 MB 435.7 kB/s eta 0:00:05
   -- ------------------------------------- 0.1/1.8 MB 744.7 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/1.8 MB 1.6 MB/s eta 0:00:01
   ----------- ---------------------------- 0.5/1.8 MB 2.7 MB/s eta 0:00:01
   ----------------- ---------------------- 0.8/1.8 MB 3.3 MB/s eta 0:00:01
   ----------------------- ---------------- 1.1/1.8 MB 3.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.4/1.8 MB 4.1 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  1.8/1.8 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 4.0 MB/s eta 0:00:00

ERROR: To modify pip, please run the following command:
D:\Tutorials\AI - Engineer\Data_Science_and_ML\.venv\Scripts\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting numpy
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.2/12.6 MB 4.6 MB/s eta 0:00:03
   - -------------------------------------- 0.4/12.6 MB 4.2 MB/s eta 0:00:03
   - -------------------------------------- 0.6/12.6 MB 4.1 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/12.6 MB 4.9 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/12.6 MB 5.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.5/12.6 MB 5.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.9/12.6 MB 5.6 MB/s eta 0:00:02
   ------- -------------------------------- 2.2/12.6 MB 6.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.6 MB 6.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 6.1 MB/s eta 0:00:02
   ---------- ----------------------------- 3.2/12.6 MB 6.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.6/12.6 MB 6.3 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.6 MB 6.4 MB/s eta 0:00:02
   ------------- -------------------------- 4.3/12.6 MB 6.5 MB/s eta 0:00:02
   -------------- ------------------------- 4.6/12.6 MB 6.5 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.6 MB 6.6 MB/s eta 0:00:02
   ---------------- ----------------------- 5.3/12.6 MB 6.7 MB/s eta 0:00:02
   ------------------ --------------------- 5.7/12.6 MB 6.7 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 6.8 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.6 MB 6.7 MB/s eta 0:00:01
   --------------------- ------------------ 6.7/12.6 MB 6.8 MB/s eta 0:00:01
   ---------------------- ----------------- 7.0/12.6 MB 6.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.4/12.6 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 6.7 MB/s eta 0:00:01
   ------------------------- -------------- 8.0/12.6 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 8.3/12.6 MB 6.8 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 6.9 MB/s eta 0:00:01
   ---------------------------- ----------- 9.0/12.6 MB 6.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.3/12.6 MB 6.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 6.9 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 6.9 MB/s eta 0:00:01
   --------------------------------- ------ 10.4/12.6 MB 7.0 MB/s eta 0:00:01
   --------------------------------- ------ 10.6/12.6 MB 7.1 MB/s eta 0:00:01
   --------------------------------- ------ 10.6/12.6 MB 7.1 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 7.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.7/12.6 MB 7.2 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  12.4/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.8 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.4.6

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\tutorials\ai - engineer\data_science_and_ml\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\tutorials\ai - engineer\data_science_and_ml\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\tutorials\ai - engineer\data_science_and_ml\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\tutorials\ai - engineer\data_science_and_ml\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB 435.7 kB/s eta 0:00:23
   ---------------------------------------- 0.1/10.0 MB 657.6 kB/s eta 0:00:16
    --------------------------------------- 0.2/10.0 MB 1.2 MB/s eta 0:00:09
   - -------------------------------------- 0.5/10.0 MB 2.2 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/10.0 MB 3.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/10.0 MB 3.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.2/10.0 MB 3.6 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/10.0 MB 4.0 MB/s eta 0:00:03
   ------- -------------------------------- 1.9/10.0 MB 4.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/10.0 MB 4.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.3/10.0 MB 4.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.7/10.0 MB 4.8 MB/s eta 0:00:02
   ----------- ---------------------------- 3.0/10.0 MB 4.7 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/10.0 MB 4.7 MB/s eta 0:00:02
   ------------- -------------------------- 3.3/10.0 MB 4.6 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/10.0 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.0/10.0 MB 4.9 MB/s eta 0:00:02
   ----------------- ---------------------- 4.4/10.0 MB 5.1 MB/s eta 0:00:02
   ------------------ --------------------- 4.7/10.0 MB 5.2 MB/s eta 0:00:02
   ------------------- -------------------- 5.0/10.0 MB 5.3 MB/s eta 0:00:01
   -------------------- ------------------- 5.2/10.0 MB 5.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/10.0 MB 5.3 MB/s eta 0:00:01
   ---------------------- ----------------- 5.6/10.0 MB 5.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/10.0 MB 5.3 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/10.0 MB 5.3 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/10.0 MB 5.3 MB/s eta 0:00:01
   --------------------------- ------------ 6.9/10.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.2/10.0 MB 5.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.5/10.0 MB 5.5 MB/s eta 0:00:01
   ------------------------------- -------- 7.8/10.0 MB 5.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/10.0 MB 5.6 MB/s eta 0:00:01
   --------------------------------- ------ 8.5/10.0 MB 5.6 MB/s eta 0:00:01
   ----------------------------------- ---- 8.8/10.0 MB 5.7 MB/s eta 0:00:01
   ------------------------------------ --- 9.1/10.0 MB 5.7 MB/s eta 0:00:01
   ------------------------------------- -- 9.3/10.0 MB 5.7 MB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 5.5 MB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.5

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [3]:
number_df = DataFrame(np.arange(0,90,3).reshape(10,3), index= ['row 1','row 2','row 3','row 4','row 5','row 6','row 7','row 8','row 9','row 10'],columns=['column 1','column 2','column 3'])
number_df

        column 1  column 2  column 3
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [4]:
number_df.iloc[0, 1]

np.int64(3)

In [5]:
number_df.iloc[0,1]=20
number_df

        column 1  column 2  column 3
row 1          0        20         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87